#%RAML 0.8
title: File Transfer Flow
version: V1
baseUri: http://0.0.0.0:8081
#uses:
protocols: [http]
mediaType: application/json
securedBy: [null]

#traits:





/file-transfer:
  #is:
  #tye:
  post:
    responses:
      200:
        body:
          application/json:
            
            
  