#%RAML 0.8
title: File Transfer Flow
version: V1
baseUri: http://0.0.0.0:8081
#uses:
protocols: [http]
securedBy: [null]
mediaType: application/json
#traits:





/file_transfer:
  /sftp_to_s3:
    /{fileName}:
      get:
        responses:
          200:
            body:
  /s3_to_sftp:
    /{fileName}:
      get:
        responses:
          200:
            body:
/file_upload:
  /sftp:
    /{fileName}:
      post:
        responses:
          200:
            body:
  /s3:
    /{fileName}:
      post:
        responses:
          200:
            body:
/file_download:
  /sftp:
    /{fileName}:
      get:
        responses:
          200:
            body:
  /s3:
    /{fileName}:
      get:
        responses:
          200:
            body:

      
            
            
  